elastica_index:
    path:     /
    defaults: { _controller: PlayWithElasticSearchBundle:Default:index }


app_playlist_tracks:
    path:     /{id}/tracks
    defaults: { _controller: PlayWithElasticSearchBundle:Default:tracks }


app_playlists_track:
    path:     /{id}/tracks/{trackId}
    defaults: { _controller: PlayWithElasticSearchBundle:Default:track }


elastica_connect:
    path:     /elastica/create-index
    defaults: { _controller: PlayWithElasticSearchBundle:Elastica:createIndex }
