app_playlists:
    path:     /
    defaults: { _controller: PlayWithElasticSearchBundle:PlayList/SearchPlayLists:searchPlayLists }

app_playlist_tracks:
    path:     /playlist/{playListId}/tracks
    defaults: { _controller: PlayWithElasticSearchBundle:Track/GetPlayListTracks:getPlayListTracks }

app_track:
    path:     /track/{trackId}
    defaults: { _controller: PlayWithElasticSearchBundle:Track/GetTrack:track }



elastica_search:
    path:     /elastica/search
    defaults: { _controller: PlayWithElasticSearchBundle:Elastica:search }
