app_playlists:
    path:     /
    defaults: { _controller: PlayWithElasticSearchBundle:PlayList/SearchPlayLists:searchPlayLists }

app_playlist_tracks:
    path:     /playlist/{playListId}/tracks
    defaults: { _controller: PlayWithElasticSearchBundle:Track/GetPlayListTracks:getPlayListTracks }

app_track:
    path:     /track/{trackId}
    defaults: { _controller: PlayWithElasticSearchBundle:Track/GetTrack:track }



elastica_create_index:
    path:     /elastica/create-index
    defaults: { _controller: PlayWithElasticSearchBundle:Elastica:createIndex }

elastica_add_document:
    path:     /elastica/add-track-document
    defaults: { _controller: PlayWithElasticSearchBundle:Elastica:addDocument }

elastica_search:
    path:     /elastica/search
    defaults: { _controller: PlayWithElasticSearchBundle:Elastica:search }

elastica_bulk_indexing:
    path: /elastica/bulk-indexing
    defaults: {_controller: PlayWithElasticSearchBundle:Elastica:tracksBulkIndexer }
