parameters:
#    atrapalo_play_with_elastic_search.example.class: Atrapalo\PlayWithElasticSearchBundle\Example

services:
    doctrine_entity_repository:
        class: Atrapalo\Infrastructure\Persistence\Doctrine\DoctrineEntityRepository
        arguments:
            - "@doctrine.orm.entity_manager"

    playlist_repository:
        class: Atrapalo\Infrastructure\Model\PlayList\Repository\PlayListRepositoryImpl
        parent: "doctrine_entity_repository"

    track_repository:
        class: Atrapalo\Infrastructure\Model\Track\Repository\TrackRepositoryImpl
        parent: "doctrine_entity_repository"
