parameters:
#    atrapalo_play_with_elastic_search.example.class: Atrapalo\PlayWithElasticSearchBundle\Example

services:
    playlist_repository:
        class: Bundle\PlayWithElasticSearchBundle\Entity\PlaylistRepository
        factory: [@doctrine, "getRepository"]
        arguments:
            - "PlayWithElasticSearchBundle:Playlist"

    track_repository:
        class: Bundle\PlayWithElasticSearchBundle\Entity\TrackRepository
        factory: [@doctrine, "getRepository"]
        arguments:
            - "PlayWithElasticSearchBundle:Track"